/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package normasapa;

import javax.swing.JButton;

/**
 *
 * @author Satellite
 */
public class APA extends javax.swing.JFrame {

    /**
     * Creates new form APA
     */
    public APA() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnLibros = new javax.swing.JButton();
        btnElectronicas = new javax.swing.JButton();
        btnPeriodicas = new javax.swing.JButton();
        Informacion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(153, 153, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 153, 0));
        lblTitulo.setText("REFERENCIAS  NORMAS  APA");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 75, -1, -1));

        btnLibros.setBackground(new java.awt.Color(51, 255, 51));
        btnLibros.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLibros.setForeground(new java.awt.Color(255, 51, 255));
        btnLibros.setText("LIBROS");
        btnLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibrosActionPerformed(evt);
            }
        });
        jPanel1.add(btnLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 257, 41));

        btnElectronicas.setBackground(new java.awt.Color(51, 255, 51));
        btnElectronicas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnElectronicas.setForeground(new java.awt.Color(255, 0, 255));
        btnElectronicas.setText("PUBLICACIONES ELECTRÓNICAS");
        btnElectronicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElectronicasActionPerformed(evt);
            }
        });
        jPanel1.add(btnElectronicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 179, -1, 38));

        btnPeriodicas.setBackground(new java.awt.Color(51, 255, 51));
        btnPeriodicas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPeriodicas.setForeground(new java.awt.Color(255, 0, 204));
        btnPeriodicas.setText("PUBLICACIONES REVISTAS");
        btnPeriodicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeriodicasActionPerformed(evt);
            }
        });
        jPanel1.add(btnPeriodicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 257, 38));

        Informacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/normasapa/images.jpg"))); // NOI18N
        Informacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InformacionMouseClicked(evt);
            }
        });
        Informacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformacionActionPerformed(evt);
            }
        });
        jPanel1.add(Informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 50, 48));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/normasapa/utpl.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 89, 150));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/normasapa/apa.JPG"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 390, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnElectronicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElectronicasActionPerformed
        Electronicas ele = new Electronicas();
        this.dispose();
        this.setVisible(true);
        ele.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnElectronicasActionPerformed

    private void btnPeriodicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeriodicasActionPerformed
        Revistas pe = new Revistas();
        this.dispose();
        this.setVisible(true);
        pe.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnPeriodicasActionPerformed

    private void btnLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibrosActionPerformed
        Libros li = new Libros();
        this.dispose();
        this.setVisible(true);
        li.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLibrosActionPerformed

    private void InformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformacionActionPerformed
       InformacionApa info = new InformacionApa();
        this.dispose();
        this.setVisible(true);
        info.setVisible(true);
// TODO add your handling code here:
      
    }//GEN-LAST:event_InformacionActionPerformed

    private void InformacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InformacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_InformacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Informacion;
    private javax.swing.JButton btnElectronicas;
    private javax.swing.JButton btnLibros;
    private javax.swing.JButton btnPeriodicas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
