/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package normasapa;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Satellite
 */
public class Libros extends javax.swing.JFrame {

    String[] apellidos = new String[100];
    String[] nombres = new String[100];
    String[] autores = new String[100];
    int contLista = 0;

    /**
     * Creates new form Generar
     */
    public Libros() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jblDato = new javax.swing.JLabel();
        jblAutor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfApellido = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        bntAgregar = new javax.swing.JButton();
        jComboBoxLista = new javax.swing.JComboBox<>();
        tfAnio = new javax.swing.JTextField();
        jblAnio = new javax.swing.JLabel();
        jblTitulo = new javax.swing.JLabel();
        tfTitulo = new javax.swing.JTextField();
        jblLugar = new javax.swing.JLabel();
        tfLugar = new javax.swing.JTextField();
        jblEditorial = new javax.swing.JLabel();
        tfEditorial = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtResultado = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jblDato.setBackground(new java.awt.Color(0, 51, 204));
        jblDato.setFont(new java.awt.Font("Vani", 1, 12)); // NOI18N
        jblDato.setText("DATOS DE BIBLIOGRAFIA");

        jblAutor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jblAutor.setText("Autor:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Apellidos");

        tfApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApellidoActionPerformed(evt);
            }
        });

        bntAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bntAgregar.setForeground(new java.awt.Color(102, 102, 102));
        bntAgregar.setText("AGREGAR");
        bntAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAgregarActionPerformed(evt);
            }
        });

        tfAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfAnioKeyTyped(evt);
            }
        });

        jblAnio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jblAnio.setText("Año de publicación: ");

        jblTitulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jblTitulo.setText("Titulo:");

        jblLugar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jblLugar.setText("Lugar de publicación");

        tfLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLugarActionPerformed(evt);
            }
        });

        jblEditorial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jblEditorial.setText("Editorial");

        btnGenerar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGenerar.setForeground(new java.awt.Color(51, 51, 51));
        btnGenerar.setText("GENERAR");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        jtResultado.setColumns(20);
        jtResultado.setRows(5);
        jScrollPane1.setViewportView(jtResultado);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nombre");

        btnBorrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 0, 51));
        btnBorrar.setText("BORRAR");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblEditorial)
                            .addComponent(jblLugar)
                            .addComponent(jblAnio)
                            .addComponent(jblTitulo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEditorial)
                            .addComponent(tfTitulo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tfLugar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jblAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxLista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfNombre)))))
                .addGap(18, 18, 18)
                .addComponent(bntAgregar)
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(127, 127, 127)
                .addComponent(jLabel2)
                .addGap(209, 209, 209))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jblDato, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jblDato, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jComboBoxLista, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(bntAgregar)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblAnio)
                    .addComponent(tfAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblLugar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblEditorial)
                    .addComponent(tfEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        if (jComboBoxLista.getItemCount() <1) {
            JOptionPane.showMessageDialog(null, "FALTA LLENAR CAMPO AUTOR");
        }else{
        GenerarApaLibro();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarActionPerformed
    public void GenerarApaLibro() {
        String autor, titulo, anio, lugar, editorial, apa;
        autor = "";
        if (contLista == 1) {
            autor = autor.concat(apellidos[0].concat(", ").concat(String.valueOf(nombres[0].charAt(0)).concat(". ")));
        } else {
            for (int i = 0; i < contLista; i++) {

                if (i == contLista - 2) {
                    autor = autor.concat(apellidos[i].concat(", ").concat(String.valueOf(nombres[i].charAt(0)).concat(". ")));
                } else if (i == contLista - 1) {
                    autor = autor.concat("& ".concat(apellidos[i]).concat(", ").concat(String.valueOf(nombres[i].charAt(0)).concat(". ")));
                } else {
                    autor = autor.concat(apellidos[i].concat(", ").concat(String.valueOf(nombres[i].charAt(0)).concat("., ")));
                }
            }
        }
        contLista = 0;
        anio = String.valueOf(tfAnio.getText());
        titulo = tfTitulo.getText();
        lugar = tfLugar.getText();
        editorial = tfEditorial.getText();
        if (tfAnio.getText().length() == 0 || tfTitulo.getText().length() == 0 || tfLugar.getText().length() == 0 || tfEditorial.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "FALTA LLENAR ALGUN CAMPO");
        } else {
            apa = autor.concat("(").concat(anio).concat("). ").concat(titulo).concat(". ").concat(lugar).concat(": ").concat(editorial).concat(".");
            jtResultado.setText(apa.concat("\n").concat(jtResultado.getText()));
        }
    }

    private void tfLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLugarActionPerformed

    private void bntAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAgregarActionPerformed
        String apellido[] = new String[100];
        String nombre[] = new String[100];
        String autor[] = new String[100];
        if (tfNombre.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "FALTA LLENAR CAMPO NOMBRE");
        } else if (tfApellido.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "FALTA LLENAR CAMPO APELLIDO");
        } else {
            autor = AgregarAutor(nombre, apellido);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_bntAgregarActionPerformed
    public String[] AgregarAutor(String nombre[], String apellido[]) {
        String[] autor = new String[100];
        jComboBoxLista.addItem(tfApellido.getText().toUpperCase().trim().concat(" ").concat(tfNombre.getText().toUpperCase().trim()));
        apellidos[contLista] = tfApellido.getText();
        nombres[contLista] = tfNombre.getText();
        tfApellido.setText(null);
        tfNombre.setText(null);
        contLista++;
        return autor;
    }
    private void tfApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfApellidoActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        tfAnio.setText(" ");
        tfTitulo.setText(" ");
        tfLugar.setText(" ");
        tfEditorial.setText(" ");
        jComboBoxLista.removeAllItems();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void tfAnioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAnioKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
        getToolkit().beep();
        evt.consume();
            JOptionPane.showMessageDialog(this, "SOLO SE ACEPTAN NÚMEROS");
        }
    }//GEN-LAST:event_tfAnioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Libros().setVisible(true);
            }
        });
    }

    public JTextField getTfAnio() {
        return tfAnio;
    }

    public void setTfAnio(JTextField tfAnio) {
        this.tfAnio = tfAnio;
    }

    public JTextArea getJtResultado() {
        return jtResultado;
    }

    public void setJtResultado(JTextArea jtResultado) {
        this.jtResultado = jtResultado;
    }

    public JTextField getTfAutor() {
        return tfApellido;
    }

    public void setTfAutor(JTextField tfAutor) {
        this.tfApellido = tfAutor;
    }

    public JTextField getTfEditorial() {
        return tfEditorial;
    }

    public void setTfEditorial(JTextField tfEditorial) {
        this.tfEditorial = tfEditorial;
    }

    public JTextField getTfLugar() {
        return tfLugar;
    }

    public void setTfLugar(JTextField tfLugar) {
        this.tfLugar = tfLugar;
    }

    public JTextField getTfTitulo() {
        return tfTitulo;
    }

    public void setTfTitulo(JTextField tfTitulo) {
        this.tfTitulo = tfTitulo;
    }

    public JComboBox<String> getjComboBoxLista() {
        return jComboBoxLista;
    }

    public void setjComboBoxLista(JComboBox<String> jComboBoxLista) {
        this.jComboBoxLista = jComboBoxLista;
    }

    public JTextField getTfApellido() {
        return tfApellido;
    }

    public void setTfApellido(JTextField tfApellido) {
        this.tfApellido = tfApellido;
    }

    public JTextField getTfNombre() {
        return tfNombre;
    }

    public void setTfNombre(JTextField tfNombre) {
        this.tfNombre = tfNombre;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JComboBox<String> jComboBoxLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblAnio;
    private javax.swing.JLabel jblAutor;
    private javax.swing.JLabel jblDato;
    private javax.swing.JLabel jblEditorial;
    private javax.swing.JLabel jblLugar;
    private javax.swing.JLabel jblTitulo;
    private javax.swing.JTextArea jtResultado;
    private javax.swing.JTextField tfAnio;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfEditorial;
    private javax.swing.JTextField tfLugar;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfTitulo;
    // End of variables declaration//GEN-END:variables
}
